apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: fiap-agro
type: Opaque
stringData:
  Jwt__Key: "CHAVE_SUPER_SECRETA_32_CHARS_OU_MAIS"
  Jwt__Issuer: "fiap-agro-identity"
  Jwt__Audience: "fiap-agro"