apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-api
  namespace: fiap-agro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: property-api
  template:
    metadata:
      labels:
        app: property-api
    spec:
      containers:
        - name: property-api
          image: fiap-agro/property:1.0
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__Default
              value: "Server=sqlserver,1433;Database=FIAPAgroProperty;User Id=sa;Password=FiapAgro2026@;TrustServerCertificate=True;Encrypt=False;"
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: Jwt__Key
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: Jwt__Audience
---
apiVersion: v1
kind: Service
metadata:
  name: property-api
  namespace: fiap-agro
spec:
  selector:
    app: property-api
  ports:
    - port: 80
      targetPort: 8080