apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-api
  namespace: fiap-agro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-api
  template:
    metadata:
      labels:
        app: ingestion-api
    spec:
      containers:
        - name: ingestion-api
          image: fiap-agro/ingestion:1.0
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__Default
              value: "Server=sqlserver,1433;Database=FIAPAgroIngestion;User Id=sa;Password=FiapAgro2026@;TrustServerCertificate=True;Encrypt=False;"
            - name: RabbitMq__HostName
              value: "rabbitmq"
            - name: RabbitMq__UserName
              value: "guest"
            - name: RabbitMq__Password
              value: "guest"
            - name: RabbitMq__Queue
              value: "sensor.readings"
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: Jwt__Key
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: Jwt__Audience
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-api
  namespace: fiap-agro
spec:
  selector:
    app: ingestion-api
  ports:
    - port: 80
      targetPort: 8080