name: Build and deploy an app to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  # Nome da imagem (ajuste para o seu)
  CONTAINER_NAME: "fiapagro"

  # Caminho do(s) manifest(s) (ajuste para o seu repo)
  # Exemplo 1: "k8s/11-property.yaml"
  # Exemplo 2: "k8s/*.yaml"
  DEPLOYMENT_MANIFEST_PATH: "k8s/*.yaml"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Login no Azure usando o JSON do Service Principal
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build e push da imagem no ACR
      - name: Build and push image to ACR
        run: |
          echo "Building and pushing to ACR..."
          az acr build \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }} \
            --registry ${{ secrets.ACR_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            .

      # kubelogin para autenticação não-interativa do AKS
      - name: Set up kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: "v0.0.25"

      # Contexto do AKS (admin false)
      - name: Get AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          admin: "false"
          use-kubelogin: "true"

      # Deploy no Kubernetes
      - name: Deploy manifests to AKS
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
          images: |
            ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
